# [PROJECT_NAME]

> ⚠️ This file was generated by /bootstrap. Replace all [TOKENS] with project-specific content.

## What This Project Is
[PROJECT_DESCRIPTION]

## Stack
- **[Primary framework]**: [How Claude should interact with it]
- **[Database/storage]**: [Conventions, schema location, migration rules]
- **[Deployment]**: Railway — see `.claude/tools/railway.md`

## Key Workflows

[Add one section per workflow from the /bootstrap intake]

### [Workflow Name]
[What Claude does, what input it receives, what output it produces.]

## Commands Available
- `/bootstrap` — Adapt .claude/ to this project
- `/virginize` — Strip files to starter-ready templates
- `/deploy` — Deploy to Railway
- `/test` — Run test suite
- `/review` — Code review a PR or file

## Agents Available
- **Reviewer** — Reviews PRs and code changes
- **Deployer** — Manages Railway deployments

## Always Follow These Rules
[Add project-specific rules here after /bootstrap]

## Environment Variables
[List required env vars with purpose — never values]

## Do Not
- Modify production database without explicit confirmation
- Commit secrets or env var values
- Deploy without passing health check
