#!/usr/bin/env python3
"""
Regenerates skills/control-plane/personas/manifest.yaml from individual .md files.
Run after adding or editing a persona file.

Reads: role → title, tone → style, domain → domain from .md files.
benchmark is manifest-only (editorial) — preserved from existing manifest.
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PERSONAS_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, "../skills/control-plane/personas"))
MANIFEST = os.path.join(PERSONAS_DIR, "manifest.yaml")

if not os.path.isdir(PERSONAS_DIR):
    print(f"Error: personas directory not found: {PERSONAS_DIR}", file=sys.stderr)
    sys.exit(1)

md_files = sorted(
    f for f in os.listdir(PERSONAS_DIR)
    if f.endswith(".md") and f != ".gitkeep"
)

if not md_files:
    print(f"No persona .md files found in {PERSONAS_DIR}", file=sys.stderr)
    sys.exit(1)

# Snapshot existing benchmark values before overwriting
existing_benchmarks: dict[str, str] = {}
if os.path.exists(MANIFEST):
    current_slug = None
    for line in open(MANIFEST):
        m = re.match(r'^  ([a-z][a-z0-9-]+):\s*$', line)
        if m:
            current_slug = m.group(1)
        bm = re.match(r'^\s+benchmark:\s+"(.+)"', line)
        if bm and current_slug:
            existing_benchmarks[current_slug] = bm.group(1)


def read_field(lines: list[str], field: str) -> str:
    for line in lines:
        if line.startswith(f"{field}:"):
            return line[len(field) + 1:].strip()
    return ""


header = """\
# CKS v6 Control Plane — Team Persona Manifest
# Auto-regenerated by scripts/generate-persona-manifest.sh
# Do not edit directly — edit the individual .md files and run the script.
#
# Token target: <400 tokens for all entries combined
# Field notes:
#   style    → maps to tone + key always-behaviors in the full .md file
#   benchmark → manifest-only discovery aid; NOT present in full .md files

personas:
"""

blocks = []
warnings = []

for filename in md_files:
    slug = filename[:-3]
    path = os.path.join(PERSONAS_DIR, filename)
    with open(path) as f:
        lines = f.readlines()

    title = read_field(lines, "role")
    if not title:
        warnings.append(f"Warning: no 'role:' field in {filename}")
        continue

    style = read_field(lines, "tone")
    domain = read_field(lines, "domain")
    benchmark = existing_benchmarks.get(slug, "")

    block = f'  {slug}:\n'
    block += f'    title: "{title}"\n'
    if style:
        block += f'    style: "{style}"\n'
    if domain:
        block += f'    domain: "{domain}"\n'
    block += f'    benchmark: "{benchmark}"\n'
    blocks.append(block)

with open(MANIFEST, "w") as f:
    f.write(header)
    f.write("\n".join(blocks))
    f.write("\n")

for w in warnings:
    print(w, file=sys.stderr)

preserved = sum(1 for b in existing_benchmarks.values() if b)
print(f"✓ Manifest written: {MANIFEST}")
print(f"  {len(blocks)} persona(s), {os.path.getsize(MANIFEST)} bytes, {preserved} benchmark(s) preserved")
