#!/bin/bash
# Regenerates skills/control-plane/personas/manifest.yaml from individual .md files.
# Run after adding or editing a persona file.
# Reads: role → title, tone → style, domain → domain from .md files.
# benchmark is manifest-only (editorial) — add manually after regeneration.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PERSONAS_DIR="$SCRIPT_DIR/../skills/control-plane/personas"
MANIFEST="$PERSONAS_DIR/manifest.yaml"

if [ ! -d "$PERSONAS_DIR" ]; then
  echo "Error: personas directory not found: $PERSONAS_DIR" >&2
  exit 1
fi

MD_FILES=$(ls "$PERSONAS_DIR"/*.md 2>/dev/null | grep -v "\.gitkeep" || true)
if [ -z "$MD_FILES" ]; then
  echo "No persona .md files found in $PERSONAS_DIR" >&2
  exit 1
fi

{
  echo "# CKS v6 Control Plane — Team Persona Manifest"
  echo "# Auto-regenerated by scripts/generate-persona-manifest.sh"
  echo "# Do not edit directly — edit the individual .md files and run the script."
  echo "#"
  echo "# Token target: <400 tokens for all entries combined"
  echo "# Field notes:"
  echo "#   style    → maps to tone + key always-behaviors in the full .md file"
  echo "#   benchmark → manifest-only discovery aid; NOT present in full .md files"
  echo ""
  echo "personas:"

  for MD_FILE in $MD_FILES; do
    SLUG=$(basename "$MD_FILE" .md)

    TITLE=$(grep "^role:" "$MD_FILE" | head -1 | sed 's/^role: *//')
    STYLE=$(grep "^tone:" "$MD_FILE" | head -1 | sed 's/^tone: *//')
    DOMAIN=$(grep "^domain:" "$MD_FILE" | head -1 | sed 's/^domain: *//')

    if [ -z "$TITLE" ]; then
      echo "  # Warning: no 'role:' field found in $(basename "$MD_FILE")" >&2
      continue
    fi

    echo "  ${SLUG}:"
    echo "    title: \"${TITLE}\""
    [ -n "$STYLE" ]  && echo "    style: \"${STYLE}\""
    [ -n "$DOMAIN" ] && echo "    domain: \"${DOMAIN}\""
    echo "    benchmark: \"\""
    echo ""
  done
} > "$MANIFEST"

COUNT=$(grep -c "^  [a-z]" "$MANIFEST" 2>/dev/null || echo 0)
SIZE=$(wc -c < "$MANIFEST" | tr -d ' ')
echo "✓ Manifest written: $MANIFEST"
echo "  ${COUNT} persona(s), ${SIZE} bytes"
echo "  Note: benchmark fields left blank — fill in manually for discovery aid"
