#!/bin/bash
# Initialize CKS project structure
# Called by /cks:bootstrap after CLAUDE.md is generated
# Creates: .prd/, .context/, .env.example, .gitignore updates

set -e

PROJECT_NAME="${1:-$(basename $(pwd))}"
TODAY=$(date +%Y-%m-%d)

echo "🔧 Initializing CKS project structure..."

# --- .prd/ ---
mkdir -p .prd
if [ ! -f ".prd/PRD-STATE.md" ]; then
  cat > .prd/PRD-STATE.md << EOF
# PRD Session State

**Last Updated:** $TODAY

## Current Position

- **Active Phase:** —
- **Phase Name:** —
- **Phase Status:** idle
- **Last Action:** Project bootstrapped
- **Last Action Date:** $TODAY
- **Next Action:** Start first feature
- **Suggested Command:** /cks:discuss

## Feature History

| PRD | Feature | Phases | Status |
|-----|---------|--------|--------|

## Session History

| Date | Phase | Action | Result |
|------|-------|--------|--------|
| $TODAY | — | Bootstrap | CKS initialized |
EOF
  echo "  ✅ .prd/PRD-STATE.md"
else
  echo "  ⏭  .prd/PRD-STATE.md (exists)"
fi

if [ ! -f ".prd/PRD-PROJECT.md" ]; then
  cat > .prd/PRD-PROJECT.md << EOF
# Project: $PROJECT_NAME

**Bootstrapped:** $TODAY

## Context

See CLAUDE.md for full project context, stack details, and conventions.
EOF
  echo "  ✅ .prd/PRD-PROJECT.md"
else
  echo "  ⏭  .prd/PRD-PROJECT.md (exists)"
fi

if [ ! -f ".prd/PRD-ROADMAP.md" ]; then
  cat > .prd/PRD-ROADMAP.md << EOF
# Roadmap

**Project:** $PROJECT_NAME
**Last Updated:** $TODAY

## Active Features

| # | Feature | Status | Phases |
|---|---------|--------|--------|

## Completed Features

| # | Feature | Completed | Phases |
|---|---------|-----------|--------|
EOF
  echo "  ✅ .prd/PRD-ROADMAP.md"
else
  echo "  ⏭  .prd/PRD-ROADMAP.md (exists)"
fi

# --- .context/ ---
mkdir -p .context
if [ ! -f ".context/config.md" ]; then
  # Detect preferred sites from package.json dependencies
  SITES=""
  if [ -f "package.json" ]; then
    grep -q "next" package.json 2>/dev/null && SITES="$SITES\n  - nextjs.org/docs"
    grep -q "react" package.json 2>/dev/null && SITES="$SITES\n  - react.dev"
    grep -q "supabase" package.json 2>/dev/null && SITES="$SITES\n  - supabase.com/docs"
    grep -q "stripe" package.json 2>/dev/null && SITES="$SITES\n  - docs.stripe.com"
    grep -q "tailwind" package.json 2>/dev/null && SITES="$SITES\n  - tailwindcss.com/docs"
    grep -q "prisma" package.json 2>/dev/null && SITES="$SITES\n  - prisma.io/docs"
    grep -q "drizzle" package.json 2>/dev/null && SITES="$SITES\n  - orm.drizzle.team/docs"
    grep -q "clerk" package.json 2>/dev/null && SITES="$SITES\n  - clerk.com/docs"
    grep -q "firebase" package.json 2>/dev/null && SITES="$SITES\n  - firebase.google.com/docs"
    grep -q "vue" package.json 2>/dev/null && SITES="$SITES\n  - vuejs.org/guide"
    grep -q "svelte" package.json 2>/dev/null && SITES="$SITES\n  - svelte.dev/docs"
  fi
  if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
    grep -q "django" requirements.txt pyproject.toml 2>/dev/null && SITES="$SITES\n  - docs.djangoproject.com"
    grep -q "fastapi" requirements.txt pyproject.toml 2>/dev/null && SITES="$SITES\n  - fastapi.tiangolo.com"
    grep -q "flask" requirements.txt pyproject.toml 2>/dev/null && SITES="$SITES\n  - flask.palletsprojects.com"
  fi

  cat > .context/config.md << EOF
---
sources:
  - context7
  - firecrawl
  - websearch
  - webfetch
auto-research: true
max-lines: 200
preferred-sites:$(echo -e "$SITES")
---
# Context Research Config — generated by /cks:bootstrap
EOF
  echo "  ✅ .context/config.md"
else
  echo "  ⏭  .context/config.md (exists)"
fi

# --- .env.example ---
if [ ! -f ".env.example" ]; then
  ENV_VARS=""
  if [ -f "package.json" ] || [ -d "src" ] || [ -d "app" ]; then
    # Scan for env var references
    ENV_VARS=$(grep -roh 'process\.env\.\w\+\|import\.meta\.env\.\w\+' src/ app/ lib/ pages/ 2>/dev/null | sed 's/process\.env\.//;s/import\.meta\.env\.//' | sort -u)
  fi
  if [ -n "$ENV_VARS" ]; then
    echo "# $PROJECT_NAME — Environment Variables" > .env.example
    echo "# Copy to .env.local and fill in values" >> .env.example
    echo "" >> .env.example
    echo "$ENV_VARS" | while read var; do
      echo "$var=" >> .env.example
    done
    echo "  ✅ .env.example ($( echo "$ENV_VARS" | wc -l | tr -d ' ') vars)"
  else
    echo "  ⏭  .env.example (no env vars detected)"
  fi
else
  echo "  ⏭  .env.example (exists)"
fi

# --- .gitignore ---
if [ -f ".gitignore" ]; then
  ADDED=0
  grep -q "^\.env$" .gitignore || { echo ".env" >> .gitignore; ADDED=$((ADDED+1)); }
  grep -q "^\.env\.local$" .gitignore || { echo ".env.local" >> .gitignore; ADDED=$((ADDED+1)); }
  grep -q "^\.env\..*" .gitignore || { echo ".env.*" >> .gitignore; ADDED=$((ADDED+1)); }
  if [ $ADDED -gt 0 ]; then
    echo "  ✅ .gitignore ($ADDED entries added)"
  else
    echo "  ⏭  .gitignore (already configured)"
  fi
else
  cat > .gitignore << EOF
# CKS
.env
.env.*
!.env.example
node_modules/
dist/
build/
.DS_Store
EOF
  echo "  ✅ .gitignore (created)"
fi

# --- .learnings/ ---
mkdir -p .learnings
echo "  ✅ .learnings/ (ready for /cks:retro)"

# --- Summary ---
echo ""
echo "✅ CKS project structure initialized"
echo ""
echo "  Files created:"
ls -1 .prd/ 2>/dev/null | sed 's/^/    .prd\//'
ls -1 .context/ 2>/dev/null | sed 's/^/    .context\//'
[ -f .env.example ] && echo "    .env.example"
echo ""
echo "  Next steps:"
echo "    /cks:go dev        Start dev server"
echo "    /cks:discuss       Plan your first feature"
echo "    /cks:help          See all commands"
